name: AdvancedWild
version: 1.2.1
api:
- 2.1.0
- 3.1.0
- 3.0.0
- 3.0.0-ALPHA5
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.1
main: Wild\Main
author: Az928
description: Advanced wild teleportation plugin!
